### ISSUE TITLE
Update documentation to refer to getting JIGSAW through conda-forge

### ISSUE THREAD

**Issue by xylar** [dengwirda/jigsaw#17]
I would recommend giving instructions for how to get JIGSAW from conda-forge.

* [Install miniconda](https://docs.conda.io/en/latest/miniconda.html)
* Add conda-forge as a channel: `conda config --add channels conda-forge`
* Create a jigsaw environment: `conda create -n jigsaw jigsaw`

Each time you want to use jigsaw:
`conda activate jigsaw`
Now `jigsaw` and `tripod` are in your run path and `libjigsaw` is in your library path with its include files in your include path.

**Comment by dengwirda** [comment]
This has been added as-is to the `0.9.10-readme`. Thanks!
