### ISSUE TITLE
Tag for 0.9.8 produces meshes that say they're using JIGSAW 0.9.9

### ISSUE THREAD

**Issue by xylar** [dengwirda/jigsaw#18]
I think the tag 0.9.8 should probably have been 0.9.9 based on the version number that appears in the generated meshes and is in `version.txt`.  It might be worth making the 0.9.9 tag and pointing it to the same commit.  I wouldn't delete the 0.9.8 tag because that would likely cause problems.  Deleting or modifying tags (even if they're wrong) is frowned upon.

**Comment by dengwirda** [comment]
This should be resolved with 0.9.10, and I'll make sure not to mess this up again!
