### ISSUE TITLE
unit test 6

### ISSUE THREAD

**Issue by xylar** [dengwirda/jigsaw#23]
When I run unit test 6 from `dev` as part of building/testing the conda package, I get:
```
test_6: /home/xylar/miniconda3/conda-bld/jigsaw_1561112951683/work/src/libcpp/containers/fixed_array.hpp:190: containers::fixed_array<D, L>::data_type& containers::fixed_array<D, L>::operator[](containers::fixed_array<D, L>::size_type) [with D = int; long unsigned int L = 2; containers::fixed_array<D, L>::data_type = int; containers::fixed_array<D, L>::size_type = long unsigned int]: Assertion `(_pos >= +0 && _pos < _size && "fixed_array[]: out of range!")' failed.
```
Any idea what's going wrong?  I'm going to disable this unit test for now.

**Comment by dengwirda** [comment]
Thanks @xylar, this should be fixed now - have corrected some iterator de-referencing in `rdel_create_init_<k>.inc`.

This should only have shown up in `debug` builds.

**Comment by xylar** [comment]
Great, that's done the trick!
