### ISSUE TITLE
question regarding output

### ISSUE THREAD

**Issue by brey** [dengwirda/jigsaw#26]
Hi Darren, I was wondering if jigsaw has an option (or it could be easy to implement) to return the index of the boundary nodes on a planar grid with specified boundaries.

**Comment by dengwirda** [comment]
@brey Yes, I think there should be an easy way to get this effect -- if you assign non-null `ID tags` to edges in the input geometry (this would be the last 'column' in the `*.msh` definition) this information will be inherited by the mesh that's generated.

This should allow you to determine which edges in the output mesh correspond to which parts of the geometry. You could then fairly easily determine the corresponding sets of boundary nodes.

**Comment by brey** [comment]
Thanks @dengwirda. It worked like a charm. I should have asked earlier before wasting a lot of time to do it post production. Lesson learned.
