### ISSUE TITLE
control option question

### ISSUE THREAD

**Issue by brey** [dengwirda/jigsaw#27]
Hi Darren, 

I am having an issue when creating a grid with given boundary. It will sometimes cross the boundary to create a shortcut. See image below. Anyway that I can avoid that, maybe a flag that I am not familiar with. My configuration is 

HFUN_SCAL = ABSOLUTE
HFUN_HMAX = Inf
HFUN_HMIN = 0.0
MESH_DIMS = 2
MESH_TOP1 = TRUE
MESH_EPS1 = 1.0
MESH_RAD2 = 1
GEOM_FEAT = TRUE

In the figure, in red dots, the input geometry and in yellow x that supposed boundary nodes that are wrong due to the highlighted element.

![Figure 13](https://user-images.githubusercontent.com/5442433/65320052-58f24200-dba1-11e9-9063-a5cae4457f3c.png)

**Comment by dengwirda** [comment]
Hi George,

From the image, I'm not sure if this is behaving as I expect or not, so if you wouldn't mind emailing me the geometry + config, etc this'd be great.

A few notes on how `JIGSAW` (should, at least) work in these cases though:

- `JIGSAW` tries to resample the geometry at the mesh-spacing that's defined. When (as in this case) the size of the "features" in the geometry is less than the local mesh spacing, elements can "span" in-between boundaries. Often this can be useful, as it can "smooth-out" unwanted detail in coastlines, etc. 

- When `mesh_top1=true` and `geom_feat=true` (as you've defined) `JIGSAW` is does additional work, refining the mesh until the topology and (sharp) geometry of the input boundaries are recovered. I'm not sure why this doesn't appear to be happening here, which is what I need to look into.

**Comment by wjlcqjd** [comment]
Hi Darren,

I just find this mesher, and not skilled to use. The quality from jigsaw is well. 
But I confuse how to define a hole? When i insert a iner ring, sometime get a hole, sometime cannot.
Is there a value to set? 

thank you!
