### ISSUE TITLE
jigsaw_load_msh_t function doesn't read vert3 coordinate data

### ISSUE THREAD

**Issue by c-ney** [dengwirda/jigsaw#28]
Steps to reproduce:

1. Produce msh file with NDIMS=3 (e.g. one of the OCTAVE example scripts)
2. Use C-API to read file

```cpp
constexpr auto filename = "MESH-3.msh";
jigsaw_msh_t handle;
jigsaw_init_msh_t(&handle);
jigsaw_load_msh_t(const_cast<char*>(filename), &handle);
```

3. Check coordinates

```cpp
std::cout << handle._vert3._data[0]._ppos[0] << '\n';  // output is 0, but probably undefined
```

The issue:

When you try reading a msh file with `NDIMS=3`, the point coordinates aren't read by `jigsaw_load_msh_t::msht_reader::push_point` because the bounds check refers to `_vert2._size` instead of `_vert3._size`. Changing this line

https://github.com/dengwirda/jigsaw/blob/a99c83491cbb0e29e20f2e6d1c090df9ecd402a6/src/liblib/load_msh_t.hpp#L208

fixes the problem.

Cheers

**Comment by dengwirda** [comment]
Thanks @c-ney , this should now be fixed in the current <a href="https://github.com/dengwirda/jigsaw/tree/dev">`dev`</a> branch.

**Comment by dengwirda** [comment]
As of 8eb2078b63c15a220dcd7b57947267af68a28dab this should be fixed in [master](https://github.com/dengwirda/jigsaw/tree/master).
