### ISSUE TITLE
Defining geometry

### ISSUE THREAD

**Issue by dengwirda** [dengwirda/jigsaw#32]
Hi Darren,

I just find this mesher, and not skilled to use. The quality from jigsaw is well. 
But I confuse how to define a hole? When i insert a iner ring, sometime get a hole, sometime cannot.
Is there a value to set? 

thank you!

_Originally posted by @wjlcqjd in https://github.com/dengwirda/jigsaw/issues/27#issuecomment-624029942_

**Comment by dengwirda** [comment]
@wjlcqjd There are a few different ways to define geometry, depending on what you're trying to do. 

By default, `jigsaw` will resample its inputs at the length scale given, so any holes smaller than this may be skipped. If you want to force all features to captured, regardless of scale, you can set `geom_feat = true` and `mesh_top1 = true`; this will make sure that all sharp corners are represented exactly, and that the topology of the input geometry is recovered. 

There are a few example programs available to help you get started:
- In `C++`: https://github.com/dengwirda/jigsaw/tree/master/uni
- In `MATLAB`: https://github.com/dengwirda/jigsaw-matlab
- In `Python`: https://github.com/dengwirda/jigsaw-python

Let me know if you have any questions.

**Comment by wjlcqjd** [comment]
By check in detail, I finded a error in my c++ code nothing to do with jigsaw. The expected result getted. Thanks you very much!

![rt](https://user-images.githubusercontent.com/64814872/81080156-03498a80-8f23-11ea-824d-f52ab788c742.png)
