### ISSUE TITLE
Add flexibility for initial distribution formats

### ISSUE THREAD

**Issue by dengwirda** [dengwirda/jigsaw#40]
Should enable reading of initial distributions in various formats, rather than just `euclidean-mesh`. 
- For `ellipsoid-mesh`, read in `lon-lat` and transform to `E^3`. 
- For `euclidean/ellipsoid-grid`, read structured arrays and convert to unstructured points, possibly with the coord transform too. Should grids induce topology? Maybe not...

**Comment by dengwirda** [comment]
This is partially addressed in [jigsaw-0.9.15.x](https://github.com/dengwirda/jigsaw/pull/43), with `ellipsoid-mesh` IC's passed as `[lon, lat] (radians)` and transformed internally to `E^3` coords.

@sbrus89, it's possible this may be of interest to you.

**Comment by sbrus89** [comment]
@dengwirda, thanks for letting me know.
