### ISSUE TITLE
Restric cmake compilation to libjigsaw only

### ISSUE THREAD

**Issue by jreniel** [dengwirda/jigsaw#46]
Is there a way to restrict the compilation to the shared library only, to avoid the overhead of compiling the executable binaries?

**Comment by dengwirda** [comment]
No not currently, it's a full build of all of the binary outputs that's done.
Reading between the lines, I suspect what you may be looking for is an easy way for users to install `jigsaw` for python-based workflows. I think the current possibility is to use the `jigsaw-conda` environment, but I suspect this also encourages a revisiting of auto-building `jigsaw` wheels for `pip`...

**Comment by jreniel** [comment]
You are on the right track. The Python interface only requires the shared library. On my CI tests, a lot of time is spent compiling the executables, which is unfortunate bc the Python interface doesn't really need them. Ideally, the shared library would be distributed as part of a `jigsawpy` wheel. I can provide some sample GitHub workflow yaml files that can be used to generate and push these wheels if you are interested.

But also, for generating the wheels it would ve useful to let CMake generate the shared library only, as again, Python doesn't require the executables.

And finally, I have nothing against conda, but I've learned to try and make sure everything can work seamlessly without it. I'd prefer to avoid conda whenever possible, although I use it sometimes to facilitate quick tests. For deployment, I'd rather build a full Python environment tailored for the task.

Thanks.



⁣Sent from BlueMail ​

**Comment by dengwirda** [comment]
I feel I'll close this for now --- I think it's safest to build the full set of jigsaw binaries in one go, and the jigsaw [conda packages](https://anaconda.org/conda-forge/jigsaw) are also available if a pre-built solution is desired.
