### ISSUE TITLE
Can Jiasaw be used as head-only libaray

### ISSUE THREAD

**Issue by GeoGroup** [dengwirda/jigsaw#51]
Dear Dr.Darren Engwirda:

The mesh quality of Jigsaw is vey high. I want to use the jigsaw to generate a mesh. It is OK to used the lib and dll after the complied. Does the Jigsaw can be used like the way of Eigen that I can put the code in the include path and use it without the compilation?
Many thanks for giving a excellent tool!

Meng

**Comment by GeoGroup** [comment]
Also I will have a try on this work.

**Comment by dengwirda** [comment]
Hi Meng,
I'd say the way to do this is to first build the jigsaw binaries and then link to the library from within your code. Trying to include the src directly would lead to more headaches than it's worth I think.
The [unit-tests](https://github.com/dengwirda/jigsaw/tree/master/uni) give some examples of how the jigsaw api can be called from within c++ programs.
