### ISSUE TITLE
how to read that *.msh file into the initial and forcing data

### ISSUE THREAD

**Issue by dinghao1995** [dengwirda/jigsaw#53]
I have compiled JIGSAW mesh tool on Linux System and run the 'ex_1.m' script to generate the 'mesh.msh' file. But how to read that *.msh file into the initial and forcing data for running the MPAS-Ocean model？

**Comment by dengwirda** [comment]
@dinghao1995, the process to build new MPAS-Ocean configurations is handled outside of jigsaw, via the scripts available in e.g. [MPAS-Tools](https://github.com/MPAS-Dev/MPAS-Tools).
As I mentioned in the [issue you opened recently](https://github.com/dengwirda/jigsaw-geo-tutorial/issues/4) though, this process is fairly involved, and generally requires input from the MPAS-Ocean team. Working with an existing configuration may be a more accessible opton: [https://e3sm.org/model/running-e3sm/e3sm-quick-start/](https://e3sm.org/model/running-e3sm/e3sm-quick-start/)
I'll close this issue for now, as the MPAS-Ocean config. + init. steps are handled outside of jigsaw.
